-- 코드를 입력하세요
SELECT d.TITLE, d.BOARD_ID, y.REPLY_ID, y.WRITER_ID, y.CONTENTS, DATE_FORMAT(y.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD d, USED_GOODS_REPLY y
WHERE d.BOARD_ID = y.BOARD_ID
AND d.CREATED_DATE LIKE '2022-10%'
ORDER BY y.CREATED_DATE, d.TITLE;